### PR TITLE
Fix AttributeError: 'Vector2' object has no attribute 'values'

### PR DESCRIPTION
**Pull request by Echelon9**
Found when running test suite, e.g. with `python setup.py test`

### CODE REVIEW

**Comment by realitix** [comment]
You are right I didn't test it for now

**Comment by realitix** [comment]
Sorry but I think I will not fix this bug that way. I will add `@properties` to a `values` function like in `Matrix` to be consistent. What do you think about that?

**Comment by realitix** [comment]
Sorry but I think I will not fix this bug that way. I will add `@properties` to a `values` function like in `Matrix` to be consistent. What do you think about that?

**Comment by Echelon9** [comment]
Happy to see you put forward an alternative PR.

**Comment by Echelon9** [comment]
Closing as issue that this PR addresses has now been resolved.

**Pull request closed without merging**
